name: mi_rutina_visual
description: Una aplicación móvil para organizar rutinas visuales para personas con autismo, síndrome de Down o discapacidad cognitiva leve.

publish_to: 'none' # Este proyecto no se publicará

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI y Material Design
  cupertino_icons: ^1.0.8
  # Selección de imágenes (galería/cámara)
  image_picker: ^1.1.2
  # Text to Speech
  flutter_tts: ^3.6.4
  # Base de datos local (SQLite)
  sqflite: ^2.3.3
  path: ^1.9.0
  # Firebase (si decides usarlo después)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  audioplayers: ^6.5.1
  numberpicker: ^2.1.1
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^17.1.2
  confetti: ^0.7.0
  firebase_storage: 12.4.10
  google_sign_in: ^6.1.0      





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/pictogramas/
    - assets/images/premios/
    - assets/google_logo.png

